create database music_database;
use music_database;
select*from artist;
show tables;

--  Display all tracks.
SELECT *
FROM track;

--  Display the track name and unit price.
SELECT name, unit_price
FROM track;

--   All tracks whose unit price is greater than 1.00.
SELECT *
FROM track
WHERE unit_price > 1.00;

--  All customers who are from India.
select*
from customer 
where country = "india"; 

-- All unique customer countries.
select 
distinct(country)
 from customer ;

--  All tracks in ascending order of unit price. 
select 
unit_price 
from track 
order by unit_price asc;

--  All tracks in descending order of unit price.
select 
unit_price 
from track 
order by unit_price desc;

--   All tracks whose unit price is 0.99.
select name, unit_price
from track 
where unit_price = 0.99;

-- Display customer first names and last names in alphabetical order.
select first_name, last_name 
from customer
 order by first_name ,last_name;

--   Tracks whose name contains the word "Love".
select*from 
track 
where name like "%love%";

-- Aggregate Functions
-- The total number of tracks.
select count(*)
as total_track 
from track ; 

--  The total number of customers.
select count(*) 
as total_no_customers
from customer;

--  The average track price.
select avg(unit_price)as average_price
from track;

--  The minimum track price.
select min(unit_price) as min_price
from track;

-- The maximum track price.
select max(unit_price) as max_price
from track;

-- Calculate the total invoice sales.
select sum(total) as total_invoice
from invoice;

-- The average invoice amount.
select avg(total) as avg_invoice
from invoice;

-- The total number of invoices.
select count(*) as total_invoices
from invoice;

-- The number of customers from India. 
select count(*) as customer_no
from customer 
where country ="india";

-- The total number of different countries.
select count(distinct(country)) as diff_country
from customer;

-- GROUP BY & HAVING
-- The number of customers in each country.
select count(customer_id),country 
from customer
group by country;

-- The number of tracks in each genre.
select genre_id,count(*) as track_no 
from track 
group by genre_id;

-- the number of tracks in each album.
select album_id,count(*) as track_no
from track 
group by album_id;

-- The number of invoices generated by each customer.
select customer_id,count(*) as invoice_num
from invoice
group by customer_id;

-- The total spending of each customer.
select customer_id,sum(total)as total_spend
from invoice
group by customer_id;

-- The average track price for each genre.
select genre_id,avg(unit_price) as avg_price
from track 
group by genre_id;

-- Display countries having two or more customers.
select country ,count(*) as cust_count
from customer
group by country
having count(*) >=2;

-- Display genres having three or more tracks.
select genre_id,count(*) as track_count
from track 
group by genre_id
having count(*)>=3;

--  The number of albums for each artist.
SELECT artist_id, COUNT(*) AS album_count
FROM album
GROUP BY artist_id;

-- Display artists who have more than one album.
SELECT artist_id, COUNT(*) AS album_count
FROM album
GROUP BY artist_id
HAVING COUNT(*) > 1;

-- INNER JOIN
-- Display track names along with their album titles.
select name,title
from track 
inner join album 
on track.album_id= album.album_id; 

-- Display album titles along with artist names.
select title,name 
from album 
inner join artist 
on album.artist_id = artist.artist_id;

-- Display track names along with their genre names.
select t.name as track_name ,g.name as genre_name 
from track t
 inner join genre g 
 on t.genre_id= g.genre_id;

-- Display customer names along with their invoice totals.
select first_name,last_name,total 
from customer 
inner join invoice
 on customer.customer_id = invoice.customer_id;
 
 -- Display customer name, invoice date, and invoice total.
 select first_name,last_name,invoice_date,total 
 from customer 
 inner join invoice
 on customer.customer_id = invoice.customer_id;
 
 --  Display artist names along with their album titles.
SELECT ar.name AS artist, a.title AS album
FROM artist ar
INNER JOIN album a
ON ar.artist_id = a.artist_id;


--  Display track name, album name, and artist name.
SELECT t.name AS track,
       a.title AS album,
       ar.name AS artist
FROM track t
INNER JOIN album a
ON t.album_id = a.album_id
INNER JOIN artist ar
ON a.artist_id = ar.artist_id;


--  Display track names belonging to the Rock genre.
SELECT t.name, g.name AS genre
FROM track t
INNER JOIN genre g
ON t.genre_id = g.genre_id
WHERE g.name = 'Rock';


--  Find the total spending of each customer.
SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spending
FROM customer c
INNER JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;


-- 40. Find the total number of tracks for each artist.
SELECT ar.name AS artist,
       COUNT(t.track_id) AS total_tracks
FROM artist ar
INNER JOIN album a
ON ar.artist_id = a.artist_id
INNER JOIN track t
ON a.album_id = t.album_id
GROUP BY ar.artist_id, ar.name;

-- LEFT JOIN
-- Display all artists and their albums, including artists without albums 
select name,title
from artist
left join album
on artist.artist_id= album.artist_id;

 -- Display all customers and their invoices.
 select c.first_name,c.last_name, i.invoice_date,i.invoice_id 
 from customer c 
 left join invoice i
 on c.customer_id = i.customer_id;
 
 --  Display all genres and their track counts
 SELECT g.name AS genre,
       COUNT(t.track_id) AS track_count
FROM genre g
LEFT JOIN track t
ON g.genre_id = t.genre_id
GROUP BY g.genre_id, g.name;

-- case when
-- Categorize tracks based on their price.
select track_id,unit_price,
 case
       WHEN unit_price >= 1.20 THEN 'Expensive'
	   WHEN unit_price >= 0.99 THEN 'Moderate'
       else "cheap"
    end as price_category
    from track;

-- Categorize invoices based on their total amount. 
select invoice_id,total, 
case
    when total>=3 then "high"
    when total>= 2 then "medium"
    else "low"
    end as invoice_category
    from invoice;

 -- Categorize customers as Domestic or International.    
 SELECT first_name,
       country,
       CASE
           WHEN country = 'India' THEN 'Domestic'
           ELSE 'International'
       END AS customer_type
FROM customer;

--  Categorize tracks as Premium or Regular.
SELECT name,
       unit_price,
       CASE
           WHEN unit_price >= 1.20 THEN 'Premium'
           ELSE 'Regular'
       END AS track_category
FROM track;

-- Categorize purchases as High Value or Normal Purchase.
SELECT invoice_id,
       total,
       CASE
           WHEN total >= 3 THEN 'High Value Customer'
           ELSE 'Normal Purchase'
       END AS purchase_type
FROM invoice;

-- project analysis
-- The most expensive track.
select name, unit_price
from track
order by unit_price desc
limit 1;

 --   The genre with the highest number of tracks.
SELECT g.name,
       COUNT(t.track_id) AS track_count
FROM genre g
INNER JOIN track t
ON g.genre_id = t.genre_id
GROUP BY g.genre_id, g.name
ORDER BY track_count DESC;
 
 --  The customer with the highest total spending.
select c.first_name, c.last_name, sum(i.total) as high_spending
from customer c
inner join invoice i
  on c.customer_id = i.customer_id
group by c.first_name, c.last_name
order by high_spending desc
limit 1;


 

 



 
 
 

 
 















